version: '3'

services:
  web:
    build: .
    entrypoint: /entrypoint.sh
    command: python Arx/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
