# Generated by Django 2.2.5 on 2019-09-12 17:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_info',
            fields=[
                ('article_id', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=20, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('headline', models.TextField()),
                ('classified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'article_info',
            },
        ),
        migrations.CreateModel(
            name='Article_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.TextField()),
                ('content_order', models.IntegerField()),
                ('content', models.TextField()),
                ('html_type', models.CharField(max_length=10)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=15, null=True)),
                ('class_conflict', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'article_content',
                'unique_together': {('article_id', 'content_order')},
            },
        ),
    ]
